In [3]:
import numpy as np

In [35]:
# Задание 1
a =np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
b = a.T
print(b)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [36]:
mean_a = np.mean(b, 0)

In [37]:
print(mean_a)

[2.  8.4]


Задание 2

In [44]:
a_centered = np.subtract(b, mean_a)
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

In [57]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
print(np.dot(a_centered[:, 0], a_centered[:, 1]))
print(a_centered_sp)

8.0
8.0


In [46]:
N = len(a_centered[:, 0])

In [47]:
a_centered_sp / (N - 1)

2.0

Задание 4

In [60]:
np.cov(a)

array([[1. , 2. ],
       [2. , 4.3]])

In [62]:
np.cov(a)[0, 1]

2.0